let first = {
    title: 'Next steps',
    content: '',
    date: '2018-07-30T15:15:42+00:00'
}

first.content += "Hello dear NW players.  \n"
first.content += "This is the first post about the NW game development. I'll try to post every monday what's happening in our awesome, incredible, focus and single man development team.  \n"
first.content += "After the initial thoughts, one thing needs to be clarify:  \n"
first.content += "**No one plays my game**  \n"
first.content += "I know that.  \n"
first.content += "And for me, that's fine. The game was made to play with my friends, so I don't think that's a huge problem right now.  \n"
first.content += "The thing is, I want to write about my thoughts on the game current state, and no one will stop me from doing it!    \n"
first.content += "**I AM THE OWNER OF MY DREAMS**  \n"
first.content += "  \n"
first.content += "## Balancing  \n"
first.content += "Explosion is strong as hell. Blink is way more valuable that Reflect shield. Followers are not that fun to use.  \n"
first.content += "The problem is the current spell set? Maybe the way spells are present in the game? \n"
first.content += "I spend some time thinking on what to do, and I found some options  \n"
first.content += "  \n"
first.content += "### Spells with prices  \n"
first.content += "You have a N amount of points and can spend this amount on spells.  \n"
first.content += "For example, you have 10 Spell Points.  \n"
first.content += "* Followers: **3 points**  \n"
first.content += "* Boomerang: **2 points**  \n"
first.content += "* Explosion: **6 points**  \n"
first.content += "* Reflect Shield: **3 points**  \n"
first.content += "* Blink: **6 points**  \n\n"
first.content += "This way, reflect shield is now a viable option, because you spend way less points than blink, for example.  \n"
first.content += "Besides, winning games, dealing more damage, killing a player, and another achievements thru the game can give you more points to spend on spells (I don't know if I like this last ideia).  \n"
first.content += "  \n"
first.content += "### Spells combo with other spells  \n"
first.content += "Let's say that fireball pushes you further away if you are on fire, and explosions give you that status (on fire).  \n"
first.content += "Now, explosion + fireball is a strong combo.  \n"
first.content += "This kind of mechanic is very versatile, giving you new options of skills combinations, wich leads to more interesting gameplay.  \n"
first.content += "  \n"
first.content += "### Enemy can see your spells  \n"
first.content += "One of my problems today with some spells is: Some of them are very good against a specific spell.  \n"
first.content += "Reflect shield can be used very easily against Followers. But, against every thing else, Blink is a way better spell to be chosen.  \n"
first.content += "If the game has a Pick Phase, like MOBAs normaly have, you could choose your spells based on what your enemy picked.  \n"
first.content += "My problem with this approach is:  \n"
first.content += "The game will slow down.  \n"
first.content += "Today, every round is very short and fast, lasting 1min 30sec top. And that's by design, I, sorry, the development team want a fast game.  \n"
first.content += "If a Pick Spell phase is introduced, I'm afraid that maybe it will last, like, half the time of the round. That's a problem? I don't know exactly, but I think know that the fun part is playing the game.  \n"
first.content += "  \n"
first.content += "After that said, I don't know exactly what option(s) to choose or even if any of them are a good idea.  \n"
first.content += "  \n"
first.content += "## Netcode refactoring  \n"
first.content += "Today, almost all of the game code is a mess. Yeah, sue me.  \n"
first.content += "But, the main issue, in my opinion, is the Netcode (and physics, but for now it's working quite well).  \n"
first.content += "I'm using way more process power that I need.  \n"
first.content += "All the requests are handled from a single process.  \n"
first.content += "It's terrible to scale.  \n"
first.content += "I can start fixing some minnor issues between each version, but, the main code must pass thru a heavy code review.  \n"
first.content += "  \n"
first.content += "## Features on the road map  \n"
first.content += "You can follow the backlog at trello  \n"
first.content += "https://trello.com/b/SZKBu6Ou/nwgame"
first.content += "  \n"
first.content += "### Animation/Sound/Music  \n"
first.content += "Animations and sounds can change the way you see a game.  \n"
first.content += "Today NW have almost no animation, and, as I'm not an artist, this part is very difficult to produce.  \n"
first.content += "My focus, at the moment, is on Gameplay, but one of the main things that I want to add in the future is a good set of animations and SFX.  \n"
first.content += "  \n"
first.content += "### Site redesing  \n"
first.content += "Yeah, it's ugly as fuck, I know.  \n"
first.content += "For now, that's fine.  \n"
first.content += "  \n"
first.content += "### AAA stuff  \n"
first.content += "Users profile, ranks, matchmaking, emojis, ingame chat. All this stuff is pretty neat to do, but, I don't going to work on it for now.  \n"

export default [
    first
]